baseURL = ""
languageCode = "en-us"
title = "AWS Lambda - Serverless"
theme = "ananke"
[params.lambdaComments]
endpoint = "https://0jve06r0hg.execute-api.us-east-2.amazonaws.com/default/student1012-comments-post"
